// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8fJQKRIDyGnZO6Knv_xjhYgX3c5_eNZs',
    appId: '1:26450284791:web:e48da990c21dcb56d603f2',
    messagingSenderId: '26450284791',
    projectId: 'geofence-1dd3d',
    authDomain: 'geofence-1dd3d.firebaseapp.com',
    storageBucket: 'geofence-1dd3d.firebasestorage.app',
    measurementId: 'G-JNCTBR6PCQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJUm3K2dY9xhGGMc2f_Na-mBOoiI31cdU',
    appId: '1:26450284791:android:64bd0001620f6684d603f2',
    messagingSenderId: '26450284791',
    projectId: 'geofence-1dd3d',
    storageBucket: 'geofence-1dd3d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwuNvViLUGIKM3wYnILa1GUNKU_wGx9k4',
    appId: '1:26450284791:ios:b55e1e7f9f47d405d603f2',
    messagingSenderId: '26450284791',
    projectId: 'geofence-1dd3d',
    storageBucket: 'geofence-1dd3d.firebasestorage.app',
    iosBundleId: 'com.example.geofence',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwuNvViLUGIKM3wYnILa1GUNKU_wGx9k4',
    appId: '1:26450284791:ios:b55e1e7f9f47d405d603f2',
    messagingSenderId: '26450284791',
    projectId: 'geofence-1dd3d',
    storageBucket: 'geofence-1dd3d.firebasestorage.app',
    iosBundleId: 'com.example.geofence',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD8fJQKRIDyGnZO6Knv_xjhYgX3c5_eNZs',
    appId: '1:26450284791:web:828bd87b5c2bc437d603f2',
    messagingSenderId: '26450284791',
    projectId: 'geofence-1dd3d',
    authDomain: 'geofence-1dd3d.firebaseapp.com',
    storageBucket: 'geofence-1dd3d.firebasestorage.app',
    measurementId: 'G-XLQR816DE3',
  );
}
